### ISSUE TITLE
Expose potion recipe as configuration option

### ISSUE THREAD

**Issue by SpiderKolo** [Alliegaytor/water-resistance-potion#3]
Since Sponges are non-renewable by default, I figured I might ask for possibly different recipe that could be made from renewable ingredients.
Why not have this potion be made with Fermented Spider Eye on Potion of Fire Resistance? Or have a config that let's you switch between the two recipe potions in case another mod touches on Fire Resistance for some reason?

Obtaining Magma Cream is a bit easier for Blazeborns and Enderians that way, and Spiders, Sugar and Brown Mushrooms could be found on land or in Nether too - all while still keeping things relatively challenging by locking this potion recipe behind Nether (or for Blazeborn - Overworld).

From non-Origin stand point, Resistance to Water seems mostly pointless unless they specifically interact with Mobs weak to water and want to protect them from it for some reason. And even in those cases you have alternatives that don't spent sponges... like drying out surrounding areas with said sponges and reusing them for other things later.

You could mitigate the problem by providing a way for sponges to be farmable/renewable, which could be a fine alternative - having your base made of nothing but sponges sounds like a fun project after all... that being said it might be better idea to keep that as separate mod/datapack.

Anyway... have a wonderful day.

**Comment by Alliegaytor** [comment]
Hi, thanks for your suggestion.

I'll look into allowing the user to specify which crafting ingredient the recipe uses. I just need to find the best api to allow for that and do some research into it.

I hadn't quite thought about sponges being non-renewable, I just used that as the recipe as it felt it somewhat made sense and I usually have a bunch of sponges in survival anyways.

It might be better if I make the default recipe an item that can fished (maybe adding in a new item - like a piece of sponge or something) so it's a bit easier to get and is also renewable.

**Comment by Alliegaytor** [comment]
@SpiderKolo, I have implemented a configurable potion recipe and have published the newest version of the mod to Modrinth.

https://modrinth.com/mod/water-resistance-potion/version/1.2.0

Please check it out and tell me if you're able to get it working to your needs :)

**Comment by SpiderKolo** [comment]
Oh... I'm making modpack for 1.20.1 so unfortunately it misses a mark for version there... though I was planning on making sponges renewable in the modpack anyway, so it's not too big of a deal as of that specific modpack.

That being said - I'm thankful for quick response on the matter!
If I'm going to make a modpack for 1.20.3 or 1.20.4, I will test the mod if it works alright.

About new default ingredient that could be used for potion: You could consider Nautilus Shells for the potion effect, as those are renewable from Drowns and from Fishing, but also are incredibly valuable so it would make the potion not as easy (though a bit easier compared to current Sponges) to come by, making Water Weakness still significant part of the Origins.

Hope you like the suggestion! :D

**Comment by Alliegaytor** [comment]
@SpiderKolo I've made a branch for the earlier 1.20 versions and have rebuilt the mod for your version. It can be found here: https://modrinth.com/mod/water-resistance-potion/version/1.2.0+1.20. Hopefully this works for you :)

The reason I have two separate versions is because the mod's dependencies keep jumping major releases and I don't want this mod to contribute to dependency hell.

I like the Nautilus Shell suggestion, I might want to have the configuration screen have preset buttons for frequently asked for items, so you don't have to type out the item manually.

Currently it just looks like this.

![image](https://github.com/Alliegaytor/water-resistance-potion/assets/61523203/7be9bdf9-9751-4885-bd05-9272f2656cbb)

**Comment by SpiderKolo** [comment]
Sorry for late response:
I'm really thankful for the backport! I will try it out on the modpack and let you know if it works for me.
