### ISSUE TITLE
unable to craft the potion

### ISSUE THREAD

**Issue by jdjfihshchcj** [Alliegaytor/water-resistance-potion#6]
hello! 
installed the mod for version 1.17.1 (fabric 0.15.6) but i am unable to craft it. the potion itself exists and works, but the crafting recipe for it isnt present, therefore its only accessible through creative mode... not quite sure what is up with it. tested the mod without any other mods and it still is uncraftable

**Comment by Alliegaytor** [comment]
@jdjfihshchcj, I've discovered what the problem is (my custom mixin plugin). I'll be able to (hopefully) fix it today. Thanks again for reporting the issue, I seriously didn't know that it wasn't working on 1.17 :)

**Comment by Alliegaytor** [comment]
I've fixed it and I also added all the mod's changes from versions 1.0.1 up to 1.3.0 (except for the configuration api). I probably won't be updating anything pre-1.19 for this mod anymore as it was a bit of a headache dealing with the older versions. But it's all sorted now!

You should be able to use this and it should be working :crossed_fingers:, please let me know if there are any issues!
https://modrinth.com/mod/water-resistance-potion/version/1.1.2+1.17.1

And thanks (again) for reporting this bug :)

**Comment by jdjfihshchcj** [comment]
hey! glad i was able to help by reporting this pesky bug :) i will test everything later today, will make sure to let you know if anythings off! also massive thank you for updating the 1.17.1 version and not patching this to newer versions because our server runs on 1.17.1 so more people can play on it... newer versions are very demanding lol. thank you for your effort!
